version: '3'
services:
  reprepro:
    container_name: reprepro
    build: 
      context: .
      args:
        - REPO_NAME=${REPO_NAME}
    ports: 
      - "2222:22"
      - "80:80"
    volumes:
      - reprepro-data:/repo
     
volumes:
  reprepro-data:

